---
title: "Assignment 5 - Interactive Visualization I and II"
author: Mahathi Gandhamaneni
output: 
  html_document:
    html_preview: false
link-citations: yes
---

```{r, include=FALSE}
library(httr)
library(tidyverse)
library(xml2)
library(stringr)
library(knitr)
library(vtable)
library(plotly)
library(widgetframe)
```

```{r, include=FALSE}

life_expectancy <- data.frame()

# List of countries to scrape
countries <- c("PRT", "DEU", "ESP", "ITA", "NLD", "GBR", "LTU", "AGO", "CPV", "GIN", "MOZ", "STP", "TUR", "BRA", "ROU", "MDA", "MEX", "UKR", "RUS", "CUB", "COL")

for (i in 1:length(countries)) {
  url <- paste0("http://api.worldbank.org/v2/country/", tolower(gsub(" ", "%20", countries[i])), "/indicator/SP.DYN.LE00.IN?date=2019")

restaurant_license_xml = as_list(read_xml(url))

xml_df = tibble::as_tibble(restaurant_license_xml) %>%
  unnest_wider(data)

lp_df = xml_df %>%
  unnest(cols = names(.)) %>%
  unnest(cols = names(.)) %>%
  # convert data type
  readr::type_convert()

# lp_df <- lp_df %>% unnest_wider(data_id)

life_expectancy <- bind_rows(life_expectancy, lp_df)

}

life_expectancy <- life_expectancy %>% select(countryiso3code, value)
life_expectancy <- cbind(Nacionality = 1:nrow(life_expectancy), life_expectancy)

df <- read.csv("dataset.csv")

# Left join
df <- merge(x=df,y=life_expectancy, 
             by="Nacionality", all.x=TRUE)
```

```{r, include=FALSE}
df <- df %>% select(Nacionality, Course, Previous.qualification, Mother.s.qualification, Father.s.qualification, Gender, Age.at.enrollment, Unemployment.rate, Target, value)
df <- rename(df, Nationality = Nacionality)
df <- rename(df, Prev_quali = Previous.qualification)
df <-rename(df, Mom_quali = Mother.s.qualification)
df <-rename(df, Dad_quali = Father.s.qualification)
df <-rename(df, Age = Age.at.enrollment)
df <-rename(df, Unemp_rate = Unemployment.rate)
df <-rename(df, Life_expectancy = value)
df <-rename(df, Program = Course)

summary(df)
# apply(df, 2, unique)
```

Almost all the categorical variables in the dataset are numerically encoded (the numeric encoding key/values can be found at <https://www.mdpi.com/2306-5729/7/11/146>). In order to simplify visualization at the moment, I have decided to leave the encoding as is.

## Visualization 1

```{r, message=FALSE, error=FALSE, warning=FALSE}
df_counts <- df %>% group_by(Age, Target) %>% count()

plot_ly(
  df_counts,
  x = ~ Age,
  y = ~ n,
  color = ~ Target,
  size = ~ n,
  type = "scatter",
  sizes = c(5, 1000),
  marker = list(sizemode = "area", opacity = .8)
) %>% 
  layout(title="Number of Students by Age and Target value", xaxis= list(title="Age"), yaxis=list(title="Count"))
```

## Visualization 2

```{r, message=FALSE, error=FALSE, warning=FALSE}
df_counts <- df %>% group_by(Program) %>% count()

plot <- ggplot(df_counts, aes(x = Program, y = n)) +
  geom_bar(stat = "identity", fill = "#4C78A8") +
  labs(title = "Number of Students by Program", x = "Program", y = "Count") +
  theme_minimal()

plotly_plot <- ggplotly(plot)
plotly_plot 
```

## Visualization 3

```{r, message=FALSE, error=FALSE, warning=FALSE}
df_counts <- df %>% group_by(Program, Target) %>% count()

plot_ly(
  df_counts,
  x = ~ Program,
  y = ~ n,
  color = ~ Target,
  size = ~ n,
  type = "scatter",
  sizes = c(5, 1000),
  marker = list(sizemode = "area", opacity = .8)
) %>% 
  layout(title="Number of Students by Program and Target value", xaxis= list(title="Program"), yaxis=list(title="Count"))
```

